#!/bin/bash
function mic() {
    if [[ $(pactl get-source-mute @DEFAULT_SOURCE@ | cut -d":" -f2 | sed 's/ //g') == "yes" ]]; then
        mic=
    else
        mic=
    fi

    echo $mic
}

#level=''
#icon=''
#STATUS=$(pactl get-sink-mute @DEFAULT_SINK@|cut -d":" -f2|sed 's/ //g')
function falante() {
    muted=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d":" -f2 | sed 's/ //g')
    level=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/%//' | head -1)
    if [[ $muted == 'yes' ]]; then
        icon=
    elif [ "$level" -le 33 ]; then
        icon=
    elif [ "$level" -le 66 ]; then
        icon=
    elif [ "$level" -le 99 ]; then
        icon=
    fi
    # echo "{\"icon\": \"$icon\", \"level\": 'Volume: $level%'}"
    echo $icon
}

function subscribe() {
    local old new
    fetch
    old="$level"
    while sleep 0.1; do
        fetch
        new="$level"
        if [ "$new" -gt "$old" ]; then
            old=$new
        elif [ "$new" -lt "$old" ]; then
            old=$new
        fi
    done
}

toggle() {
    if [ $STATUS == "false" ]; then
        pactl set-sink-mute 0 toggle
        dunstfy --icon=volume-level-muted --urgency=normal "Volume is muted." "Volume has been muted, your PC has been shut the fucked up."
    else
        pactl set-sink-mute 0 toggle
        dunstify --icon=volume-level-high --urgency=normal "Volume has been turned on." "Sound is now on, you will hear farts!"
    fi
}

if [[ $1 == "--icon" ]]; then
    falante
elif [[ $1 == "--mic" ]]; then
    mic
fi
