#!/bin/bash

status=$(nmcli g | grep -oE "disconectado")
essid=$(nmcli c | grep wlp3s0 | awk '{print ($1)}')
sinal=$(awk 'NR==3 {printf("%.0f\n",$3*10/7)}' /proc/net/wireless)

    if [[ "$sinal" -ge "75" ]]; then
        icone = ""
    elif [[ "$sinal" -ge "50" ]]; then
        icone = ""
    elif [[ "$sinal" -ge "25" ]]; then
        icone = ""
    elif [[ "$sinal" -ge "0" ]]; then
        icone = ""
    else
        icone = ""
    fi


if [ $status ] ; then
    icon=$icone
    text=""
    col="#575268"

else
    icon=$icone
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

