#!/bin/bash

status=$(nmcli g | grep -oE "disconectado")
essid=$(nmcli c | grep wlp3s0 | awk '{print ($1)}')
#sinal=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)


if [ $status ] ; then
    icon=""
    text=""
    col="#575268"

else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

