#!/usr/bin/zsh

status=$(nmcli g | grep -oE "disconectado")
essid=$(nmcli c | grep wlp3s0 | awk '{print ($1)}')
sinal=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

getIcon() {
    if [[ $sinal -ge "75" ]]; then
        echo ""
    elif [[ $sinal -ge "50" ]]; then
        echo ""
    elif [[ $sinal -ge "25" ]]; then
        echo ""
    elif [[ $sinal -ge "0" ]]; then
        echo ""
    else
        echo ""
    fi
}

if [ $status ] ; then
    icon=getIcon()
    text=""
    col="#575268"

else
    icon=getIcon()
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

